-- 테이블 삭제
DROP TABLE IF EXISTS CATEGORY CASCADE;
DROP TABLE IF EXISTS CONTENTS_OTT CASCADE;
DROP TABLE IF EXISTS MEMBER_CONTENTS CASCADE;
DROP TABLE IF EXISTS OTT CASCADE;
DROP TABLE IF EXISTS CONTENTS CASCADE;
DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS REVIEW CASCADE;

-- 테이블 생서
-- REVIEW 테이블 생성
CREATE TABLE IF NOT EXISTS REVIEW
(
	REVIEW_NO INTEGER(255) PRIMARY KEY AUTO_INCREMENT COMMENT '리뷰 번호',
    REVIEW_DATE DATE NOT NULL DEFAULT(CURRENT_DATE) COMMENT '리뷰 날짜',
    REVIEW_SCORE INTEGER(10) NOT NULL COMMENT '리뷰 점수',
    REVIEW_CONTENT VARCHAR(255) NOT NULL COMMENT '리뷰 내용'
) 
	ENGINE=INNODB COMMENT '리뷰';

-- MEMBER 테이블 생성
CREATE TABLE IF NOT EXISTS MEMBER
(
	MEMBER_NO INTEGER(255) PRIMARY KEY AUTO_INCREMENT COMMENT '회원 번호',
	MEMBER_NAME VARCHAR(30) NOT NULL COMMENT '회원 이름',
	NICKNAME VARCHAR(30) NOT NULL COMMENT '닉네임',
	ID VARCHAR(30) NOT NULL COMMENT '아이디',
	PW VARCHAR(255) NOT NULL COMMENT '비밀번호',
	EMAIL VARCHAR(30) NOT NULL COMMENT '이메일',
	PHONE VARCHAR(15) COMMENT '연락처'
) 
	ENGINE=INNODB COMMENT '회원';

-- CATEGORY 테이블 생성
CREATE TABLE IF NOT EXISTS CATEGORY
(
	CATEGORY_NO INTEGER(255) PRIMARY KEY AUTO_INCREMENT COMMENT '카테고리 번호',
    CATEGORY_NAME VARCHAR(10) NOT NULL COMMENT '카테고리 이름'
) 
	ENGINE=INNODB COMMENT '카테고리';

-- CONTENTS 테이블 생성
CREATE TABLE IF NOT EXISTS CONTENTS 
(
	CONTENTS_NO INTEGER(255) PRIMARY KEY AUTO_INCREMENT COMMENT '콘텐츠 번호',
    CONTENTS_NAME VARCHAR(100) NOT NULL COMMENT '콘텐츠 명',
    CREATOR_NAME VARCHAR(30) NOT NULL COMMENT '작가/감독 이름',
    RELEASE_YEAR YEAR COMMENT '출품 연도',
    IMAGE_URL VARCHAR(100) COMMENT '이미지 URL',
    CATEGORY_NO INTEGER(255) COMMENT '카테고리 번호',
    CONSTRAINT FK_CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO) ON DELETE SET NULL
)
	ENGINE=INNODB COMMENT '콘텐츠';

-- OTT 테이블 생성
CREATE TABLE IF NOT EXISTS OTT
(
	OTT_NO INTEGER(255) PRIMARY KEY AUTO_INCREMENT COMMENT 'OTT 번호',
    OTT_NAME VARCHAR(10) NOT NULL COMMENT 'OTT 이름'
) 
	ENGINE=INNODB COMMENT 'OTT';
    
-- MEMBER_CONTENT 테이블 생성
CREATE TABLE IF NOT EXISTS MEMBER_CONTENTS
(
	CONTENTS_NO INTEGER(255) COMMENT 'OTT 번호',
	MEMBER_NO INTEGER(255) COMMENT 'OTT 번호',
	REVIEW_NO INTEGER(255) COMMENT 'OTT 번호',
    CONSTRAINT FK_CONTENTS_NO FOREIGN KEY (CONTENTS_NO) REFERENCES CONTENTS (CONTENTS_NO) ON DELETE CASCADE,
	CONSTRAINT FK_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO) ON DELETE CASCADE,
	CONSTRAINT FK_REVIEW_NO FOREIGN KEY (REVIEW_NO) REFERENCES REVIEW (REVIEW_NO) ON DELETE CASCADE
) 
	ENGINE=INNODB COMMENT '회원별 콘텐츠 리뷰';

-- CONTENTS_OTT 테이블 생성
CREATE TABLE IF NOT EXISTS CONTENTS_OTT
(
	CONTENTS_NO INTEGER(255) COMMENT 'OTT 번호',
	OTT_NO INTEGER(255) COMMENT 'OTT 번호',
    CONSTRAINT FK_CONTENTS_ID FOREIGN KEY (CONTENTS_NO) REFERENCES CONTENTS (CONTENTS_NO) ON DELETE CASCADE,
	CONSTRAINT FK_OTT_NO FOREIGN KEY (OTT_NO) REFERENCES OTT (OTT_NO) ON DELETE SET NULL
) 
	ENGINE=INNODB COMMENT '콘텐츠별 OTT';
